[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
task_token = "5sD5JB67WPjJkZuNDDVVv3owPogc7dft8yZc76ccqB7A"

[programs.devnet]
task_token = "5sD5JB67WPjJkZuNDDVVv3owPogc7dft8yZc76ccqB7A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/main-wallet.json"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[deploy]
task_token = "target/deploy/task_token-keypair.json"
